Add photoionization schema
XENONnT/xedocs pull request #94
Opened 2023-07-28 13:21 UTC by shenyangshi

As @xzh19980906 will show [today](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenonnt:zihao:sr1_s2aft_photonionization_correction) the time-dependent corrections can be build using linear correlation with photoionization strength. I propose we store these values too in the corrections, and use this to make all SR1 relative/absolute LY/QY corrections.

2023-07-28 13:35 UTC, jmosbacher requested changes
Thanks @shenyangshi. This PR needs some cleaning.

- There are changes to all the notebooks in this commit that dont look relevant to the change.
- There are two redundant schemas in two separate files, one of them should be removed.

2023-07-28 13:37 UTC, shenyangshi commented
Thanks @jmosbacher, only realized this we I started the draft PR, now it seems ok.

2023-07-28 14:25 UTC, jmosbacher commented on xedocs/schemas/corrections/photoionization_strength.py
> +    _ALIAS = "photoionization_strength"
```suggestion
    _ALIAS = "photoionization_strengths"
```

2023-07-31 11:33 UTC, shenyangshi commented
Hi @jmosbacher, do you think this PR is ready to be merged?

2023-07-31 11:38 UTC, merged